version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  gateway_system:
#    image: puzanovim/gateway_system:v2
    build: gateway_system
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - library_system
      - rating_system
      - reservation_system

  library_system:
    image: puzanovim/library_system:v1
    container_name: library
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  rating_system:
    image: puzanovim/rating_system:v1
    container_name: rating
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  reservation_system:
    image: puzanovim/reservation_system:v1
    container_name: reservation
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - postgres

volumes:
  db-data: