domain: puzanovim.com
service:
  port: 8080
  profile: k8s
  image:
    name:
    version:
  database:
    name:
    host: postgres
    port: 5432
    username: program
    password: test
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
