name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GATEWAY_SERVICE_IMAGE: puzanovim/gateway_system:v3
  LIBRARY_SYSTEM_IMAGE: puzanovim/library_system:v1
  RATING_SYSTEM_IMAGE: puzanovim/rating_system:v1
  RESERVATION_SYSTEM_IMAGE: puzanovim/reservation_system:v1

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push services
        run: |
          docker build -t ${{ env.GATEWAY_SERVICE_IMAGE }} gateway_system && docker push ${{ env.GATEWAY_SERVICE_IMAGE }}
          docker build -t ${{ env.LIBRARY_SYSTEM_IMAGE }} library_system && docker push ${{ env.LIBRARY_SYSTEM_IMAGE }}
          docker build -t ${{ env.RATING_SYSTEM_IMAGE }} rating_system && docker push ${{ env.RATING_SYSTEM_IMAGE }}
          docker build -t ${{ env.RESERVATION_SYSTEM_IMAGE }} reservation_system && docker push ${{ env.RESERVATION_SYSTEM_IMAGE }}

      - name: Deploy
        run: |
          kubectl config set-cluster k8s --server="${{ secrets.SERVER_URL }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials main-admin --token="${{ secrets.SA_TOKEN }}"
          kubectl config set-context default --cluster=k8s --user=main-admin
          kubectl config use-context default
          
          cd k8s
          helm upgrade services ./services-chart         
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"